#!/usr/bin/env python

import sys
import time
import threading
import os
import hashlib
import socket

from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

sys.path.append('gen-py')

from tritonTransfer import transfer
from tritonTransfer.ttypes import *

BLOCK_SIZE = 16000
SERVER_REDUNDANCY = 2

# Block Servers
blockServers = []

# Metadata store
metadata = {}

# hash location store
hashLocations = {}

# the handler that contains the methods specified in the thrift file
class transferHandler:


    def __init__(self):
        pass


    def registerBlockServer(self, port):

        # Add the new server into the structure
        blockServers.append(socket.gethostbyname(socket.gethostname()) + ':' + str(port))

        # Make sure that the new server inside our structure
        for server in blockServers:
            if server == socket.gethostbyname(socket.gethostname()) + ':' + str(port):
                return 'OK'
        return 'ERROR'


    def uploadFile(self, fileName, hashlist):

        # Get only the filename and not the path
        fileName = os.path.basename(fileName)

        # Add the file metadata into the metadata store
        metadata[fileName] = hashlist

        # Keep track of the blocks that have not yet been updated
        missingBlocks = []

        # Loop through all things in the hashlist to determine what exists
        for i in hashlist:
            if not hashLocations.has_key(i) and i not in missingBlocks:

                # Find the block servers with the least amount of items
                blockCount = {}
                for server in blockServers:
                    blockCount[server] = 0
                for hash in hashLocations:
                    blockCount[hashLocations[hash][0]] += 1
                    blockCount[hashLocations[hash][1]] += 1

                # Upload to the servers we identified
                uploadToServers = map(lambda x: x[0], sorted(blockCount.items(), key=lambda x: x[1]))[:SERVER_REDUNDANCY]

                hashLocations[i] = uploadToServers
                missingBlocks.append(str({'servers': uploadToServers, 'hash': i}))

        # Sends the missing blocks back to the client
        return missingBlocks


    def downloadFile(self, fileName):

        downloadLocations = []

        # check the metadata store for the blocks
        if metadata.has_key(fileName):
            for hash in metadata[fileName]:
                downloadLocations.append(str({'servers': hashLocations[hash], 'hash': hash}))

        return downloadLocations


###############################################################################
# MAIN
###############################################################################

# Ensure that the right number of command line parameters were given
if len(sys.argv) != 2:
    print('Usage: tt-md-server <server_port>')
    sys.exit(0)

# Set the port number
portNum = int(sys.argv[1])

handler = transferHandler()
processor = transfer.Processor(handler)
transport = TSocket.TServerSocket(port=portNum)
tfactory = TTransport.TBufferedTransportFactory()
pfactory = TBinaryProtocol.TBinaryProtocolFactory()

server = TServer.TThreadedServer(processor, transport, tfactory, pfactory)

server.serve()